version: "1.0.1"

auth:
  type: "none"
  client_id: ""
  callback_uri: ""

entry_points:
  - entry_point_key: "PLUGIN_CONFIGURATION"
    artifact_id: "configs"
    route: "/"

admin_launchers:
  id: "admin-launcher-01"
  name: "Testes Automacoes"
  route: "/"
